{"name": "test_wrong_password", "status": "passed", "attachments": [{"name": "log", "source": "1a7ac8ca-4231-40a0-ab19-24acf9e64d88-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d5a7532d-0c55-48ef-8fa4-0fb063c6b668-attachment.txt", "type": "text/plain"}], "start": 1746189740027, "stop": 1746189767809, "uuid": "13675091-d9ce-4401-8c48-b826d3a7d6dc", "historyId": "87369211eabcbcbe3213a423ec74cc54", "testCaseId": "87369211eabcbcbe3213a423ec74cc54", "fullName": "projekt_zaliczeniowy.tests.testy_logowania.test_bledne_haslo#test_wrong_password", "labels": [{"name": "story", "value": "Logowanie z użyciem błędnego hasła"}, {"name": "feature", "value": "Logowanie"}, {"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "projekt_zaliczeniowy.tests.testy_logowania"}, {"name": "suite", "value": "test_bledne_haslo"}, {"name": "host", "value": "DESKTOP-4S3FS01"}, {"name": "thread", "value": "24476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "projekt_zaliczeniowy.tests.testy_logowania.test_bledne_haslo"}]}